version: "3.3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      FLASK_ENV: development
    ports:
      - "27017:27017"

  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017

volumes:
  mongo_data:
